#  Outlier Gene Set Analysis
#
#  cite with PMID: 24277953
#  Ochs et al IEEE/ACM Trans Comput Biol Bioinform 2013
#
#  outMap - creates PDF color map of where outliers occur
#           coded for molecular type
#
#  Inputs: outList - list with all outliers generated by outCallRank
#                    or outCallTib
#          geneList - gene set to compare to
#          hmName - name for PDF output file
#          plotName - header for plot
#          truncGene - if TRUE, only include genes that have outlier
#                      in the plot, default is all genes in gene set
#          clust - if TRUE, clusters data and produces dendrograms
#
#  Output: a matrix used for generating heatmap
#
#  v 1.0 - Michael Ochs, TCNJ, 15 Jan 2014
outMap <- function(outList, geneList, hmName = 'PatSpecMap.pdf', plotName = 'Outliers',truncGene = FALSE, clust=FALSE) {

    require(gplots)

    bits <- c(1,2,4,8,16,32,64) # max data types = 7
    colors <- c('black','red','green','yellow','blue','purple','cyan','white')

    nType <- length(outList)
    temp <- outList[[1]]
    nTum <- dim(temp)[2]
    patNames <- colnames(temp)
    geneNames <- rownames(temp) %in% geneList
    geneNames <- rownames(temp)[geneNames]
	nGene <- length(geneNames)
    nGenePlot <- nGene

	tMap <- matrix(nrow=nTum+2,ncol=nGene)
	tMap[,] <- 0
    
    for (i in 1:length(outList)) {
        temp <- outList[[i]]
        temp2 <- rownames(temp) %in% geneList
        temp <- t(temp[temp2,])
        temp <- bits[i] * temp
        tMap[1:nTum,] <- tMap[1:nTum,] + temp
    }


	colnames(tMap) <- geneNames
	rownames(tMap) <- c(patNames,"","Range")

	nAffect <- sum(rowSums(tMap) > 0)
	nGeneOut <- sum(colSums(tMap) > 0)
    
    if (truncGene) {
        keep <- colSums(tMap) > 0
        tMap <- tMap[,keep]
        nGenePlot <- nGeneOut
    }
    
    nStep <- floor(nGenePlot/7)
    for (i in 1:7) {
        n1 <- ((i-1)*nStep)+1
        n2 <- i*nStep
        tMap[nTum+2,n1:n2] <- i
    }
    

	yLabel <- paste(nAffect,'Patients with Outlier from',nTum,'Total')
	xLabel <- paste(nGeneOut,'Genes with Outlier from',nGene,'Total') 


	xLab <- min(30.0/nGenePlot,1)
	yLab <- min(30.0/nTum,1)
    
    colRange = c(0,2^nType-1)
    
	pdf(hmName)
    if (clust==FALSE) {
        heatmap.2(tMap,scale='none',Rowv=NA,Colv=NA,trace='none',
			  cexRow=yLab,cexCol=xLab,col=colors,
              main=plotName,xlab=xLabel,ylab=yLabel,zlim=colRange,
              dendrogram='none')
    } else {
        heatmap.2(tMap[1:nTum,],scale='none',trace='none',
        cexRow=yLab,cexCol=xLab,col=colors,
        main=plotName,xlab=xLabel,ylab=yLabel,zlim=colRange)
    }
	dev.off()

	return(tMap)
}
  